= Tomu FPGA - Design Test (DVT) of **Production** Tomu FPGA Board (Fomu)

This directory contains the **design validation** version of the **production** Tomu FPGA. The
production version is designed for mass production. It uses advanced PCB
technologies which are harder for the average maker and hobbyist to access.

This is a test model an is **NOT INTENDED FOR PRODUCTION**.  You probably want
the PVT version.

These features are;

* Laser drilled and blind vias -- this allows industry standard footprints for
  the WCSP parts, increasing long term reliability of the solder joints.

* Hard gold plating of USB pads and touch pads. This is designed to increase
  reliability and the number of insertions and removals before failure.

You get a production version if you order from https://xobs.io/[Sean 'xobs' Cross] https://j.mp/fomu-cs[through or after the Crowd Supply campaign].

== PCB Specification

CAUTION: This PCB specification has issues and should not be produced.  Use PVT instead!

[width="100%",cols=">h,"]
|================================================================
|                        Board Size | 0.37 x 0.51 inches (9.5 x 13.1mm)
|                   Board thickness | 0.6mm
|                  Number of Layers | 4
|                        Components | Single Side
|                        Silkscreen | None
|           Number of through holes | 1
| Minimum trace width and clearance | 0.1mm track width, minimum clearance is 0.1mm
|                     Vias + Drills
a|
* Between layers 1 and 2 - Laser-drilled - 0.2mm/0.1mm blind vias
* Between layers 3 and 4 - Laser-drilled - 0.2mm/0.1mm blind vias
* Between layers 2 and 3 - Mechanical - 0.5mm/0.2mm buried vias
|               Smallest pitch size | 0201 resistors, WCSP parts
|                 Control Impedance | Not required
|                 Solder Mask color | Blue
|                           Plating
a|
* ENIG on the top.
* Hard gold on the fingers on the underside.
* Hard gold on the edge of the top.

|                          Material | FR4
|================================================================

== Bill of Materials

[format="csv",cols="^1,11*2",options="header"]
|===================================================
Reference,Value,Description,Datasheet,Manufacturer,MPN,Alt Manufacturer,Alt PN,Alt MPN,Digikey PN,DNP?,Count
C10,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C9,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C8,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C3,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C1,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C2,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
U9,USB-B,PCB-etched USB pads,,DNP,DNP,,,,,X,1
U10,RGB-LED,,https://www.cree.com/led-components/media/documents/ds-UHD1110-FKA.pdf,Cree,UHD1110-FKA,Citizen,CL-505S-X-SD-T,,N/A,,1
R12,"0201, 22ohm, 1/16W, 1%",,,ANY,ANY,,,,,,1
R11,"0201, 22ohm, 1/16W, 1%",,,ANY,ANY,,,,,,1
R9,"0201, 1.5k, 1/16W, 1%",,,ANY,ANY,,,,,,1
C4,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
SW2,Captouch Pads,PCB-etched captouch pads,,DNP,DNP,,,,,X,1
R1,"0201, 10k, 1/16W",,,ANY,ANY,,,,,,1
R5,"0201, 10k, 1/16W",,,ANY,ANY,,,,,,1
C21,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C24,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C28,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C5,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C7,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C22,"0402, 10uF, 6.3V, X5R, 20%",,,ANY,ANY,,,,,,1
C23,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C25,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
U7,Crystal Oscillator,XTAL OSC XO 48.0000MHZ CMOS SMD,https://www.ecsxtal.com/store/pdf/ECS-2520MV.pdf,ECS,XC2756CT-ND,,,,XC2756CT-ND,,1
C11,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
U5,ICE40UP5K-UWG30,"ICE40-ULTRAPLUS, 5280 LUTS, 1.2V",http://www.latticesemi.com/Products/FPGAandCPLD/iCE40Ultra,Lattice,ICE40UP5K-UWG30ITR,,,," 	ICE40UP5K-UWG30ITR-ND ",,1
U4,SPI Flash,IC FLASH 128M SPI 133MHZ 8SOIC,http://www.winbond.com/resource-files/w25q128jv_dtr%20revc%2003272018%20plus.pdf,GigaDevice Semiconductor (HK) Limited,GD25Q16CEIGR,Macronix,MX25R1635FZUIH0,,1970-1011-6-ND,,1
U1,LDO-X2SON-1.2V,,http://www.ti.com/lit/ds/symlink/lp5907.pdf,TI,LP5907SNX-1.2/NOPB,Microchip,576-4305-1-ND,MIC5504-1.2YMT,,,1
U2,LDO-X2SON-3.3V,,http://www.ti.com/lit/ds/symlink/lp5907.pdf,TI,LP5907SNX-3.3/NOPB,Microchip,576-4305-1-ND,MIC5504-3.3YMT,296-39066-2-ND ,,1
U3,LDO-X2SON-2.5V,,http://www.ti.com/lit/ds/symlink/lp5907.pdf,TI,LP5907SNX-2.5/NOPB,Microchip,576-4305-1-ND,MIC5504-2.5YMT,296-40371-2-ND,,1
TP2,Testpoint,,,,,,,,,X,1
TP3,Testpoint,,,,,,,,,X,1
TP4,Testpoint,,,,,,,,,X,1
TP5,Testpoint,,,,,,,,,X,1
TP6,Testpoint,,,,,,,,,X,1
TP7,Testpoint,,,,,,,,,X,1
TP8,Testpoint,,,,,,,,,X,1
TP9,Testpoint,,,,,,,,,X,1
TP1,Testpoint,,,,,,,,,X,1
TP12,Testpoint,,,,,,,,,X,1
TP10,Testpoint,,,,,,,,,X,1
TP11,Testpoint,,,,,,,,,X,1
XX1,Touchpad Mask Removal,,,DNP,DNP,,,,,X,1
XX2,Case,"Case for Tomu, customized for FPGA",,Jiada,Tomu-FPGA-Case,,,,,X,1
XX3,ESD Bag,ESD bag containing case and PCBA,,ANY,Tomu-ESD-Bag,,,,,X,1
D1,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D2,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D3,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D4,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D6,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D7,D5V0L1B2LP3-7,,https://www.diodes.com/assets/Datasheets/D5V0L1B2LP3.pdf,Diodes Incorporated,D5V0L1B2LP3-7,,,,,,1
D5,VCUT05E1-SD0,,http://www.vishay.com/docs/85900/vcut05e1-sd0.pdf,Vishay Semiconductor Diodes Division,VCUT05E1-SD0-G4-08,,,,,,1
R10,"0201, 100ohm, 1/16W, 1%",,,ANY,ANY,,,,,,1
C20,"0201, 100nF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
C17,"0201, 1uF, 10V, X5R, 20%",,,ANY,ANY,,,,,,1
|===================================================

== Images

* TBD

